#!/usr/bin/python3

import sys


def factorize_num(num):
    my_list = []
    for i in range(2, num // 2 + 1):
        if num % i == 0:
            my_list.append((i, num / i))
            break;

    return my_list


with open(sys.argv[1], "r") as file:
    numbers = file.read().splitlines()

for num in numbers:
    num = int(num)
    new_list = factorize_num(num)
    for i in new_list:
        p, q = i
        print(f"{num}={q}*{p}")
